## static_countries
UPDATE static_countries SET cn_short_pl = 'Andora', cn_official_name_pl = 'Księstwo Andory', cn_capital_pl = 'Andora' WHERE cn_iso_2 = 'AD';
UPDATE static_countries SET cn_short_pl = 'Zjednoczone Emiraty Arabskie', cn_capital_pl = 'Abu Zabi' WHERE cn_iso_2 = 'AE';
UPDATE static_countries SET cn_short_pl = 'Afganistan', cn_official_name_pl = 'Islamska Republika Afganistanu', cn_capital_pl = 'Kabul' WHERE cn_iso_2 = 'AF';
UPDATE static_countries SET cn_short_pl = 'Antigua i Barbuda', cn_capital_pl = 'Saint John’s' WHERE cn_iso_2 = 'AG';
UPDATE static_countries SET cn_short_pl = 'Anguilla', cn_capital_pl = 'The Valley' WHERE cn_iso_2 = 'AI';
UPDATE static_countries SET cn_short_pl = 'Albania', cn_official_name_pl = 'Republika Albanii', cn_capital_pl = 'Tirana' WHERE cn_iso_2 = 'AL';
UPDATE static_countries SET cn_short_pl = 'Armenia', cn_official_name_pl = 'Republika Armenii', cn_capital_pl = 'Erywań' WHERE cn_iso_2 = 'AM';
UPDATE static_countries SET cn_short_pl = 'Angola', cn_capital_pl = 'Luanda' WHERE cn_iso_2 = 'AO';
UPDATE static_countries SET cn_short_pl = 'Antarktyda' WHERE cn_iso_2 = 'AQ';
UPDATE static_countries SET cn_short_pl = 'Argentyna', cn_official_name_pl = 'Republika Argentyńska', cn_capital_pl = 'Buenos Aires' WHERE cn_iso_2 = 'AR';
UPDATE static_countries SET cn_short_pl = 'Samoa Amerykańskie', cn_capital_pl = 'Fagatogo' WHERE cn_iso_2 = 'AS';
UPDATE static_countries SET cn_short_pl = 'Austria', cn_official_name_pl = 'Republika Austrii', cn_capital_pl = 'Wiedeń' WHERE cn_iso_2 = 'AT';
UPDATE static_countries SET cn_short_pl = 'Australia', cn_capital_pl = 'Canberra' WHERE cn_iso_2 = 'AU';
UPDATE static_countries SET cn_short_pl = 'Aruba', cn_capital_pl = 'Oranjestad' WHERE cn_iso_2 = 'AW';
UPDATE static_countries SET cn_short_pl = 'Azerbejdżan', cn_official_name_pl = 'Republika Azerbejdżanu', cn_capital_pl = 'Baku' WHERE cn_iso_2 = 'AZ';
UPDATE static_countries SET cn_short_pl = 'Bośnia i Hercegowina', cn_capital_pl = 'Sarajewo' WHERE cn_iso_2 = 'BA';
UPDATE static_countries SET cn_short_pl = 'Barbados', cn_capital_pl = 'Bridgetown' WHERE cn_iso_2 = 'BB';
UPDATE static_countries SET cn_short_pl = 'Bangladesz', cn_official_name_pl = 'Ludowa Republika Bangladeszu', cn_capital_pl = 'Dhaka' WHERE cn_iso_2 = 'BD';
UPDATE static_countries SET cn_short_pl = 'Belgia', cn_official_name_pl = 'Królestwo Belgii', cn_capital_pl = 'Bruksela' WHERE cn_iso_2 = 'BE';
UPDATE static_countries SET cn_short_pl = 'Burkina Faso', cn_capital_pl = 'Wagadugu' WHERE cn_iso_2 = 'BF';
UPDATE static_countries SET cn_short_pl = 'Bułgaria', cn_official_name_pl = 'Republika Bułgarii', cn_capital_pl = 'Sofia' WHERE cn_iso_2 = 'BG';
UPDATE static_countries SET cn_short_pl = 'Bahrajn', cn_official_name_pl = 'Królestwo Bahrajnu', cn_capital_pl = 'Manama' WHERE cn_iso_2 = 'BH';
UPDATE static_countries SET cn_short_pl = 'Burundi', cn_official_name_pl = 'Republika Burundi', cn_capital_pl = 'Bużumbura' WHERE cn_iso_2 = 'BI';
UPDATE static_countries SET cn_short_pl = 'Benin', cn_capital_pl = 'Porto-Novo' WHERE cn_iso_2 = 'BJ';
UPDATE static_countries SET cn_short_pl = 'Bermudy', cn_capital_pl = 'Hamilton' WHERE cn_iso_2 = 'BM';
UPDATE static_countries SET cn_short_pl = 'Brunei', cn_official_name_pl = 'Brunei Darussalam', cn_capital_pl = 'Bandar Seri Begawan' WHERE cn_iso_2 = 'BN';
UPDATE static_countries SET cn_short_pl = 'Boliwia', cn_official_name_pl = 'Wielonarodowe Państwo Boliwia', cn_capital_pl = 'Sucre' WHERE cn_iso_2 = 'BO';
UPDATE static_countries SET cn_short_pl = 'Brazylia', cn_official_name_pl = 'Federacyjna Republika Brazylii', cn_capital_pl = 'Brasília' WHERE cn_iso_2 = 'BR';
UPDATE static_countries SET cn_short_pl = 'Bahamy', cn_capital_pl = 'Nassau' WHERE cn_iso_2 = 'BS';
UPDATE static_countries SET cn_short_pl = 'Bhutan', cn_official_name_pl = 'Wspólnota Bahamów', cn_capital_pl = 'Thimphu' WHERE cn_iso_2 = 'BT';
UPDATE static_countries SET cn_short_pl = 'Wyspa Bouveta' WHERE cn_iso_2 = 'BV';
UPDATE static_countries SET cn_short_pl = 'Botswana', cn_capital_pl = 'Gaborone', cn_official_name_pl = 'Republika Botswany' WHERE cn_iso_2 = 'BW';
UPDATE static_countries SET cn_short_pl = 'Białoruś', cn_official_name_pl = 'Republika Białorusi', cn_capital_pl = 'Mińsk' WHERE cn_iso_2 = 'BY';
UPDATE static_countries SET cn_short_pl = 'Belize', cn_capital_pl = 'Belmopan' WHERE cn_iso_2 = 'BZ';
UPDATE static_countries SET cn_short_pl = 'Kanada', cn_capital_pl = 'Ottawa' WHERE cn_iso_2 = 'CA';
UPDATE static_countries SET cn_short_pl = 'Wyspa Kokosowa' WHERE cn_iso_2 = 'CC';
UPDATE static_countries SET cn_short_pl = 'Kongo', cn_official_name_pl = 'Demokratyczna Republika Kongo', cn_capital_pl = 'Brazzaville' WHERE cn_iso_2 = 'CD';
UPDATE static_countries SET cn_short_pl = 'Republika Środkowoafrykańska', cn_capital_pl = 'Bangi' WHERE cn_iso_2 = 'CF';
UPDATE static_countries SET cn_short_pl = 'Kongo - Brazzaville', cn_official_name_pl = 'Republika Konga' WHERE cn_iso_2 = 'CG';
UPDATE static_countries SET cn_short_pl = 'Szwajcaria', cn_official_name_pl = 'Konfederacja Szwajcarska', cn_capital_pl = 'Berno' WHERE cn_iso_2 = 'CH';
UPDATE static_countries SET cn_short_pl = 'Wybrzeże Kości Słoniowej', cn_official_name_pl = 'Republika Wybrzeża Kości Słoniowej', cn_capital_pl = 'Jamusukro' WHERE cn_iso_2 = 'CI';
UPDATE static_countries SET cn_short_pl = 'Wyspy Cooka', cn_capital_pl = 'Avarua' WHERE cn_iso_2 = 'CK';
UPDATE static_countries SET cn_short_pl = 'Chile', cn_official_name_pl = 'Republika Chile', cn_capital_pl = 'Santiago' WHERE cn_iso_2 = 'CL';
UPDATE static_countries SET cn_short_pl = 'Kamerun', cn_official_name_pl = 'Republika Kamerunu', cn_capital_pl = 'Jaunde' WHERE cn_iso_2 = 'CM';
UPDATE static_countries SET cn_short_pl = 'Chiny', cn_official_name_pl = 'Chińska Republika Ludowa', cn_capital_pl = 'Pekin' WHERE cn_iso_2 = 'CN';
UPDATE static_countries SET cn_short_pl = 'Kolumbia', cn_official_name_pl = 'Republika Kolumbii', cn_capital_pl = 'Bogota' WHERE cn_iso_2 = 'CO';
UPDATE static_countries SET cn_short_pl = 'Kostaryka', cn_official_name_pl = 'Republika Kostaryki', cn_capital_pl = 'San José' WHERE cn_iso_2 = 'CR';
UPDATE static_countries SET cn_short_pl = 'Kuba', cn_official_name_pl = 'Republika Kuby', cn_capital_pl = 'Hawana' WHERE cn_iso_2 = 'CU';
UPDATE static_countries SET cn_short_pl = 'Republika Zielonego Przylądka', cn_capital_pl = 'Praia' WHERE cn_iso_2 = 'CV';
UPDATE static_countries SET cn_short_pl = 'Wyspa Bożego Narodzenia', cn_capital_pl = 'Flying Fish Cove' WHERE cn_iso_2 = 'CX';
UPDATE static_countries SET cn_short_pl = 'Cypr', cn_official_name_pl = 'Republika Cypryjska', cn_capital_pl = 'Nikozja' WHERE cn_iso_2 = 'CY';
UPDATE static_countries SET cn_short_pl = 'Czechy', cn_official_name_pl = 'Republika Czeska', cn_capital_pl = 'Praga' WHERE cn_iso_2 = 'CZ';
UPDATE static_countries SET cn_short_pl = 'Niemcy', cn_official_name_pl = 'Republika Federalna Niemiec', cn_capital_pl = 'Berlin' WHERE cn_iso_2 = 'DE';
UPDATE static_countries SET cn_short_pl = 'Dżibuti', cn_official_name_pl = 'Republika Dżibuti', cn_capital_pl = cn_short_pl WHERE cn_iso_2 = 'DJ';
UPDATE static_countries SET cn_short_pl = 'Dania', cn_official_name_pl = 'Królestwo Danii', cn_capital_pl = 'Kopenhaga' WHERE cn_iso_2 = 'DK';
UPDATE static_countries SET cn_short_pl = 'Dominika', cn_official_name_pl = 'Wspólnota Dominiki', cn_capital_pl = 'Roseau' WHERE cn_iso_2 = 'DM';
UPDATE static_countries SET cn_short_pl = 'Dominikana', cn_official_name_pl = 'Republika Dominikańska', cn_capital_pl = 'Santo Domingo' WHERE cn_iso_2 = 'DO';
UPDATE static_countries SET cn_short_pl = 'Algieria', cn_official_name_pl = 'Algierska Republika Ludowo-Demokratyczna', cn_capital_pl = 'Algier' WHERE cn_iso_2 = 'DZ';
UPDATE static_countries SET cn_short_pl = 'Ekwador', cn_official_name_pl = 'Republika Ekwadoru', cn_capital_pl = 'Quito' WHERE cn_iso_2 = 'EC';
UPDATE static_countries SET cn_short_pl = 'Estonia', cn_official_name_pl = 'Republika Estońska', cn_capital_pl = 'Tallinn' WHERE cn_iso_2 = 'EE';
UPDATE static_countries SET cn_short_pl = 'Egipt', cn_official_name_pl = 'Arabska Republika Egiptu', cn_capital_pl = 'Kair' WHERE cn_iso_2 = 'EG';
UPDATE static_countries SET cn_short_pl = 'Sahara Zachodnia', cn_official_name_pl = 'Saharyjska Arabska Republika Demokratyczna', cn_capital_pl = 'Al-Ujun' WHERE cn_iso_2 = 'EH';
UPDATE static_countries SET cn_short_pl = 'Erytrea', cn_capital_pl = 'Asmara' WHERE cn_iso_2 = 'ER';
UPDATE static_countries SET cn_short_pl = 'Hiszpania', cn_official_name_pl = 'Królestwo Hiszpanii', cn_capital_pl = 'Madryt' WHERE cn_iso_2 = 'ES';
UPDATE static_countries SET cn_short_pl = 'Etiopia', cn_official_name_pl = 'Federalna Demokratyczna Republika Etiopii', cn_capital_pl = 'Addis Abeba' WHERE cn_iso_2 = 'ET';
UPDATE static_countries SET cn_short_pl = 'Finlandia', cn_official_name_pl = 'Republika Finlandii', cn_capital_pl = 'Helskiki' WHERE cn_iso_2 = 'FI';
UPDATE static_countries SET cn_short_pl = 'Fidżi', cn_official_name_pl = 'Republika Wysp Fidżi', cn_capital_pl = 'Suva' WHERE cn_iso_2 = 'FJ';
UPDATE static_countries SET cn_short_pl = 'Falklandy', cn_capital_pl = 'Stanley' WHERE cn_iso_2 = 'FK';
UPDATE static_countries SET cn_short_pl = 'Mikronezja', cn_official_name_pl = 'Sfederowane Stany Mikronezji', cn_capital_pl = 'Palikir' WHERE cn_iso_2 = 'FM';
UPDATE static_countries SET cn_short_pl = 'Wyspy Owcze', cn_capital_pl = 'Thorshavn' WHERE cn_iso_2 = 'FO';
UPDATE static_countries SET cn_short_pl = 'Francja', cn_official_name_pl = 'Republika Francuska', cn_capital_pl = 'Paryż' WHERE cn_iso_2 = 'FR';
UPDATE static_countries SET cn_short_pl = 'Gabon', cn_official_name_pl = 'Republika Gabońska', cn_capital_pl = 'Libreville' WHERE cn_iso_2 = 'GA';
UPDATE static_countries SET cn_short_pl = 'Wielka Brytania', cn_official_name_pl = 'Zjednoczone Królestwo Wielkiej Brytanii i Irlandii Północnej', cn_capital_pl = 'Londyn' WHERE cn_iso_2 = 'GB';
UPDATE static_countries SET cn_short_pl = 'Grenada', cn_capital_pl = 'Saint George’s' WHERE cn_iso_2 = 'GD';
UPDATE static_countries SET cn_short_pl = 'Gruzia', cn_official_name_pl = 'Demokratyczna Republika Gruzji', cn_capital_pl = 'Tbilisi' WHERE cn_iso_2 = 'GE';
UPDATE static_countries SET cn_short_pl = 'Gujana Francuska', cn_capital_pl = 'Kajenna' WHERE cn_iso_2 = 'GF';
UPDATE static_countries SET cn_short_pl = 'Ghana', cn_official_name_pl = 'Republika Ghany', cn_capital_pl = 'Akra' WHERE cn_iso_2 = 'GH';
UPDATE static_countries SET cn_short_pl = 'Gibraltar', cn_capital_pl = cn_short_pl WHERE cn_iso_2 = 'GI';
UPDATE static_countries SET cn_short_pl = 'Grenlandia', cn_capital_pl = 'Nuuk' WHERE cn_iso_2 = 'GL';
UPDATE static_countries SET cn_short_pl = 'Gambia', cn_official_name_pl = 'Republika Gambii', cn_capital_pl = 'Bandżul' WHERE cn_iso_2 = 'GM';
UPDATE static_countries SET cn_short_pl = 'Gwinea', cn_official_name_pl = 'Republika Gwinei', cn_capital_pl = 'Konakry' WHERE cn_iso_2 = 'GN';
UPDATE static_countries SET cn_short_pl = 'Gwadelupa', cn_official_name_pl = 'Departament Zamorski Francji', cn_capital_pl = 'Basse-Terre' WHERE cn_iso_2 = 'GP';
UPDATE static_countries SET cn_short_pl = 'Gwinea Równikowa', cn_official_name_pl = 'Republika Gwinei Równikowej', cn_capital_pl = 'Malabo' WHERE cn_iso_2 = 'GQ';
UPDATE static_countries SET cn_short_pl = 'Grecja', cn_official_name_pl = 'Republika Grecka', cn_capital_pl = 'Ateny' WHERE cn_iso_2 = 'GR';
UPDATE static_countries SET cn_short_pl = 'Georgia Południowa i Sandwich Południowy', cn_capital_pl = 'King Edward Point' WHERE cn_iso_2 = 'GS';
UPDATE static_countries SET cn_short_pl = 'Gwatemala', cn_capital_pl = cn_short_pl WHERE cn_iso_2 = 'GT';
UPDATE static_countries SET cn_short_pl = 'Guam', cn_short_pl = 'Hagåtña' WHERE cn_iso_2 = 'GU';
UPDATE static_countries SET cn_short_pl = 'Gwinea Bissau', cn_official_name_pl = 'Republika Gwinei Bissau', cn_capital_pl = 'Bissau' WHERE cn_iso_2 = 'GW';
UPDATE static_countries SET cn_short_pl = 'Gujana', cn_official_name_pl = 'Kooperacyjna Republika Gujany', cn_capital_pl = 'Georgetown' WHERE cn_iso_2 = 'GY';
UPDATE static_countries SET cn_short_pl = 'Hongkong', cn_official_name_pl = 'Specjalny Region Administracyjny Hongkong' WHERE cn_iso_2 = 'HK';
UPDATE static_countries SET cn_short_pl = 'Honduras', cn_official_name_pl = 'Republika Hondurasu' WHERE cn_iso_2 = 'HN';
UPDATE static_countries SET cn_short_pl = 'Chorwacja', cn_official_name_pl = 'Republika Chorwacji', cn_capital_pl = 'Tegucigalpa' WHERE cn_iso_2 = 'HR';
UPDATE static_countries SET cn_short_pl = 'Haiti', cn_official_name_pl = 'Republika Haiti', cn_capital_pl = 'Port-au-Prince' WHERE cn_iso_2 = 'HT';
UPDATE static_countries SET cn_short_pl = 'Węgry', cn_official_name_pl = 'Republika Węgierska', cn_capital_pl = 'Budapeszt' WHERE cn_iso_2 = 'HU';
UPDATE static_countries SET cn_short_pl = 'Indonezja', cn_capital_pl = 'Dżakarta' WHERE cn_iso_2 = 'ID';
UPDATE static_countries SET cn_short_pl = 'Irland', cn_capital_pl = 'Dublin' WHERE cn_iso_2 = 'IE';
UPDATE static_countries SET cn_short_pl = 'Izrael', cn_capital_pl = 'Tel Awiw-Jafa' WHERE cn_iso_2 = 'IL';
UPDATE static_countries SET cn_short_pl = 'Indie', cn_official_name_pl = 'Republika Indii', cn_capital_pl = 'Nowe Delhi' WHERE cn_iso_2 = 'IN';
UPDATE static_countries SET cn_short_pl = 'Brytyjskie Terytorium Oceanu Indyjskiego' WHERE cn_iso_2 = 'IO';
UPDATE static_countries SET cn_short_pl = 'Irak', cn_official_name_pl = 'Republika Iraku', cn_capital_pl = 'Bagdad' WHERE cn_iso_2 = 'IQ';
UPDATE static_countries SET cn_short_pl = 'Iran', cn_official_name_pl = 'Islamska Republika Iranu', cn_capital_pl = 'Teheran' WHERE cn_iso_2 = 'IR';
UPDATE static_countries SET cn_short_pl = 'Islandia', cn_capital_pl = 'Reykjavík' WHERE cn_iso_2 = 'IS';
UPDATE static_countries SET cn_short_pl = 'Włochy', cn_official_name_pl = 'Republika Włoska', cn_capital_pl = 'Rzym' WHERE cn_iso_2 = 'IT';
UPDATE static_countries SET cn_short_pl = 'Jamajka', cn_capital_pl = 'Kingston' WHERE cn_iso_2 = 'JM';
UPDATE static_countries SET cn_short_pl = 'Jordania', cn_official_name_pl = 'Jordańskie Królestwo Haszymidzkie', cn_capital_pl = 'Amman' WHERE cn_iso_2 = 'JO';
UPDATE static_countries SET cn_short_pl = 'Japonia', cn_capital_pl = 'Tokjo' WHERE cn_iso_2 = 'JP';
UPDATE static_countries SET cn_short_pl = 'Kenia', cn_official_name_pl = 'Republika Kenii', cn_capital_pl = 'Nairobi' WHERE cn_iso_2 = 'KE';
UPDATE static_countries SET cn_short_pl = 'Kirgistan', cn_official_name_pl = 'Republika Kirgiska', cn_capital_pl = 'Biszkek' WHERE cn_iso_2 = 'KG';
UPDATE static_countries SET cn_short_pl = 'Kambodża', cn_official_name_pl = 'Królestwo Kambodży', cn_capital_pl = 'Phnom Penh' WHERE cn_iso_2 = 'KH';
UPDATE static_countries SET cn_short_pl = 'Kiribati', cn_official_name_pl = 'Republika Kiribati', cn_capital_pl = 'Bairiki' WHERE cn_iso_2 = 'KI';
UPDATE static_countries SET cn_short_pl = 'Komory', cn_official_name_pl = 'Związek Komorów', cn_capital_pl = 'Moroni'  WHERE cn_iso_2 = 'KM';
UPDATE static_countries SET cn_short_pl = 'Saint Kitts i Nevis', cn_official_name_pl = 'Saint Kitts i Nevis', cn_capital_pl = 'Basseterre' WHERE cn_iso_2 = 'KN';
UPDATE static_countries SET cn_short_pl = 'Korea Północna', cn_official_name_pl = 'Republika Ludowo-Demokratyczna', cn_capital_pl = 'Pjongjang' WHERE cn_iso_2 = 'KP';
UPDATE static_countries SET cn_short_pl = 'Korea Południowa', cn_official_name_pl = 'Republika Korei', cn_capital_pl = 'Seul' WHERE cn_iso_2 = 'KR';
UPDATE static_countries SET cn_short_pl = 'Kuwejt', cn_capital_pl = cn_short_pl WHERE cn_iso_2 = 'KW';
UPDATE static_countries SET cn_short_pl = 'Kajmany', cn_capital_pl = 'George Town' WHERE cn_iso_2 = 'KY';
UPDATE static_countries SET cn_short_pl = 'Kazachstan', cn_official_name_pl = 'Republika Kazachstanu', cn_capital_pl = 'Astana' WHERE cn_iso_2 = 'KZ';
UPDATE static_countries SET cn_short_pl = 'Laos', cn_official_name_pl = 'Laotańska Republika Ludowo-Demokratyczna', cn_capital_pl = 'Wientian' WHERE cn_iso_2 = 'LA';
UPDATE static_countries SET cn_short_pl = 'Liban', cn_capital_pl = 'Bejrut' WHERE cn_iso_2 = 'LB';
UPDATE static_countries SET cn_short_pl = 'Saint Lucia', cn_capital_pl = 'Castries' WHERE cn_iso_2 = 'LC';
UPDATE static_countries SET cn_short_pl = 'Liechtenstein', cn_official_name_pl = 'Księstwo Liechtenstein', cn_capital_pl = 'Vaduz' WHERE cn_iso_2 = 'LI';
UPDATE static_countries SET cn_short_pl = 'Sri Lanka', cn_official_name_pl = 'Demokratyczna Socjalistyczna Republika Sri Lanka', cn_capital_pl = 'Sri Dźajawardanapura Kotte' WHERE cn_iso_2 = 'LK';
UPDATE static_countries SET cn_short_pl = 'Liberia', cn_official_name_pl = 'Republika Liberii', cn_capital_pl = 'Monrovia' WHERE cn_iso_2 = 'LR';
UPDATE static_countries SET cn_short_pl = 'Lesotho', cn_capital_pl = 'Maseru' WHERE cn_iso_2 = 'LS';
UPDATE static_countries SET cn_short_pl = 'Litwa', cn_official_name_pl = 'Republika Litewska', cn_capital_pl = 'Wilno' WHERE cn_iso_2 = 'LT';
UPDATE static_countries SET cn_short_pl = 'Luksemburg', cn_official_name_pl = 'Wielkie Księstwo Luksemburga', cn_capital_pl = cn_short_pl WHERE cn_iso_2 = 'LU';
UPDATE static_countries SET cn_short_pl = 'Łotwa', cn_official_name_pl = 'Republika Łotewska', cn_capital_pl = 'Ryga' WHERE cn_iso_2 = 'LV';
UPDATE static_countries SET cn_short_pl = 'Libia', cn_official_name_pl = 'Wielka Arabska Libijska Dżamahirijja Ludowo-Socjalistyczna', cn_capital_pl = 'Trypolis' WHERE cn_iso_2 = 'LY';
UPDATE static_countries SET cn_short_pl = 'Marokko', cn_official_name_pl = 'Królestwo Marokańskie', cn_capital_pl = 'Rabat' WHERE cn_iso_2 = 'MA';
UPDATE static_countries SET cn_short_pl = 'Monako', cn_official_name_pl = 'Księstwo Monako', cn_capital_pl = cn_short_pl WHERE cn_iso_2 = 'MC';
UPDATE static_countries SET cn_short_pl = 'Mołdawia', cn_official_name_pl = 'Republika Mołdawii', cn_capital_pl = 'Kiszyniów' WHERE cn_iso_2 = 'MD';
UPDATE static_countries SET cn_short_pl = 'Madagaskar', cn_official_name_pl = 'Republika Madagaskaru', cn_capital_pl = 'Antananarywa' WHERE cn_iso_2 = 'MG';
UPDATE static_countries SET cn_short_pl = 'Wyspy Marshalla', cn_official_name_pl = 'Republika Wysp Marshalla', cn_capital_pl = 'Majuro' WHERE cn_iso_2 = 'MH';
UPDATE static_countries SET cn_short_pl = 'Macedonia', cn_official_name_pl = 'Republika Macedonii', cn_capital_pl = 'Skopje' WHERE cn_iso_2 = 'MK';
UPDATE static_countries SET cn_short_pl = 'Mali', cn_official_name_pl = 'Republika Mali', cn_capital_pl = 'Bamako' WHERE cn_iso_2 = 'ML';
UPDATE static_countries SET cn_short_pl = 'Birma', cn_official_name_pl = 'Republika Związku Mianma' WHERE cn_iso_2 = 'MM';
UPDATE static_countries SET cn_short_pl = 'Mongolia', cn_capital_pl = 'Ułan Bator' WHERE cn_iso_2 = 'MN';
UPDATE static_countries SET cn_short_pl = 'Makau', cn_official_name_pl = 'Specjalny Region Administracyjny Makau' WHERE cn_iso_2 = 'MO';
UPDATE static_countries SET cn_short_pl = 'Mariany Północne', cn_official_name_pl = 'Wspólnota Marianów Północnych', cn_capital_pl = 'Capital Hill' WHERE cn_iso_2 = 'MP';
UPDATE static_countries SET cn_short_pl = 'Martynika', cn_capital_pl = 'Fort-de-France' WHERE cn_iso_2 = 'MQ';
UPDATE static_countries SET cn_short_pl = 'Mauretania', cn_official_name_pl = 'Islamska Republika Mauretańska', cn_capital_pl = 'Nawakszut' WHERE cn_iso_2 = 'MR';
UPDATE static_countries SET cn_short_pl = 'Montserrat', cn_capital_pl = 'Plymouth' WHERE cn_iso_2 = 'MS';
UPDATE static_countries SET cn_short_pl = 'Malta', cn_official_name_pl = 'Republika Malty', cn_capital_pl = 'Valletta' WHERE cn_iso_2 = 'MT';
UPDATE static_countries SET cn_short_pl = 'Mauritius', cn_capital_pl = 'Port Louis' WHERE cn_iso_2 = 'MU';
UPDATE static_countries SET cn_short_pl = 'Malediwy', cn_official_name_pl = 'Republika Państwa Wysp', cn_capital_pl = 'Male' WHERE cn_iso_2 = 'MV';
UPDATE static_countries SET cn_short_pl = 'Malawi', cn_official_name_pl = 'Republika Malawi', cn_capital_pl = 'Lilongwe' WHERE cn_iso_2 = 'MW';
UPDATE static_countries SET cn_short_pl = 'Meksyk', cn_official_name_pl = 'Meksykańskie Stany Zjednoczone', cn_capital_pl = cn_short_pl WHERE cn_iso_2 = 'MX';
UPDATE static_countries SET cn_short_pl = 'Malezja', cn_capital_pl = 'Kuala Lumpur' WHERE cn_iso_2 = 'MY';
UPDATE static_countries SET cn_short_pl = 'Mozambik', cn_official_name_pl = 'Republika Mozambiku', cn_capital_pl = 'Maputo' WHERE cn_iso_2 = 'MZ';
UPDATE static_countries SET cn_short_pl = 'Namibia', cn_official_name_pl = 'Republika Namibii', cn_capital_pl = 'Windhuk' WHERE cn_iso_2 = 'NA';
UPDATE static_countries SET cn_short_pl = 'Nowa Kaledonia', cn_capital_pl = 'Numea' WHERE cn_iso_2 = 'NC';
UPDATE static_countries SET cn_short_pl = 'Niger', cn_official_name_pl = 'Republika Nigru', cn_capital_pl = 'Niamey' WHERE cn_iso_2 = 'NE';
UPDATE static_countries SET cn_short_pl = 'Wyspa Norfolk', cn_official_name_pl = 'Terytorium Wyspy Norfolk', cn_capital_pl = 'Kingston' WHERE cn_iso_2 = 'NF';
UPDATE static_countries SET cn_short_pl = 'Nigeria', cn_official_name_pl = 'Federalna Republika Nigerii', cn_capital_pl = 'Abudża' WHERE cn_iso_2 = 'NG';
UPDATE static_countries SET cn_short_pl = 'Nikaragua', cn_official_name_pl = 'Republika Nikaragui', cn_capital_pl = 'Managua' WHERE cn_iso_2 = 'NI';
UPDATE static_countries SET cn_short_pl = 'Holandia', cn_official_name_pl = 'Królestwa Niderlandów', cn_capital_pl = 'Amsterdam' WHERE cn_iso_2 = 'NL';
UPDATE static_countries SET cn_short_pl = 'Norwegia', cn_official_name_pl = 'Królestwo Norwegii', cn_capital_pl = 'Oslo' WHERE cn_iso_2 = 'NO';
UPDATE static_countries SET cn_short_pl = 'Nepal', cn_official_name_pl = 'Federalna Demokratyczna Republika Nepalu', cn_capital_pl = 'Katmandu' WHERE cn_iso_2 = 'NP';
UPDATE static_countries SET cn_short_pl = 'Nauru', cn_official_name_pl = 'Republika Nauru', cn_capital_pl = 'Yaren' WHERE cn_iso_2 = 'NR';
UPDATE static_countries SET cn_short_pl = 'Niue', cn_capital_pl = 'Alofi' WHERE cn_iso_2 = 'NU';
UPDATE static_countries SET cn_short_pl = 'Nowa Zelandia', cn_capital_pl = 'Wellington' WHERE cn_iso_2 = 'NZ';
UPDATE static_countries SET cn_short_pl = 'Oman', cn_official_name_pl = 'Sułtanat Omanu', cn_capital_pl = 'Maskat' WHERE cn_iso_2 = 'OM';
UPDATE static_countries SET cn_short_pl = 'Panama', cn_official_name_pl = 'Republika Panamy', cn_capital_pl = cn_short_pl WHERE cn_iso_2 = 'PA';
UPDATE static_countries SET cn_short_pl = 'Peru', cn_official_name_pl = 'Republika Peru', cn_capital_pl = 'Lima' WHERE cn_iso_2 = 'PE';
UPDATE static_countries SET cn_short_pl = 'Polinezja Francuska', cn_capital_pl = 'Papeete' WHERE cn_iso_2 = 'PF';
UPDATE static_countries SET cn_short_pl = 'Papua-Nowa Gwinea', cn_official_name_pl = 'Niezależne Państwo Papui-Nowej Gwinei', cn_capital_pl = 'Port Moresby' WHERE cn_iso_2 = 'PG';
UPDATE static_countries SET cn_short_pl = 'Filipiny', cn_official_name_pl = 'Republika Filipin', cn_capital_pl = 'Manila' WHERE cn_iso_2 = 'PH';
UPDATE static_countries SET cn_short_pl = 'Pakistan', cn_official_name_pl = 'Islamska Republika Pakistanu', cn_capital_pl = 'Islamabad' WHERE cn_iso_2 = 'PK';
UPDATE static_countries SET cn_short_pl = 'Polska', cn_official_name_pl = 'Rzeczpospolita Polska', cn_capital_pl = 'Warszawa' WHERE cn_iso_2 = 'PL';
UPDATE static_countries SET cn_short_pl = 'Saint-Pierre i Miquelon', cn_official_name_pl = 'Wspólnota Terytorialna Saint-Pierre i Miquelon', cn_capital_pl = 'Saint-Pierre' WHERE cn_iso_2 = 'PM';
UPDATE static_countries SET cn_short_pl = 'Pitcairn', cn_capital_pl = 'Adamstown' WHERE cn_iso_2 = 'PN';
UPDATE static_countries SET cn_short_pl = 'Portoryko', cn_capital_pl = 'San Juan' WHERE cn_iso_2 = 'PR';
UPDATE static_countries SET cn_short_pl = 'Portugalia', cn_official_name_pl = 'Republika Portugalska', cn_capital_pl = 'Lizbona' WHERE cn_iso_2 = 'PT';
UPDATE static_countries SET cn_short_pl = 'Palau', cn_official_name_pl = 'Republika Palau', cn_capital_pl = 'Ngerulmud' WHERE cn_iso_2 = 'PW';
UPDATE static_countries SET cn_short_pl = 'Paragwaj', cn_official_name_pl = 'Republika Paragwaju', cn_capital_pl = 'Asunción' WHERE cn_iso_2 = 'PY';
UPDATE static_countries SET cn_short_pl = 'Katar', cn_capital_pl = 'Doha' WHERE cn_iso_2 = 'QA';
UPDATE static_countries SET cn_short_pl = 'Reunion', cn_capital_pl = 'Saint-Denis' WHERE cn_iso_2 = 'RE';
UPDATE static_countries SET cn_short_pl = 'Rumunia', cn_capital_pl = 'Bukareszt' WHERE cn_iso_2 = 'RO';
UPDATE static_countries SET cn_short_pl = 'Rosja', cn_official_name_pl = 'Federacja Rosyjska', cn_capital_pl = 'Moskwa' WHERE cn_iso_2 = 'RU';
UPDATE static_countries SET cn_short_pl = 'Rwanda', cn_official_name_pl = 'Republika Rwandy', cn_capital_pl = 'Kigali' WHERE cn_iso_2 = 'RW';
UPDATE static_countries SET cn_short_pl = 'Arabia Saudyjska', cn_official_name_pl = 'Królestwo Arabii Saudyjskiej', cn_capital_pl = 'Rijad' WHERE cn_iso_2 = 'SA';
UPDATE static_countries SET cn_short_pl = 'Wyspy Salomona', cn_capital_pl = 'Honiara' WHERE cn_iso_2 = 'SB';
UPDATE static_countries SET cn_short_pl = 'Seszele', cn_capital_pl = 'Victoria' WHERE cn_iso_2 = 'SC';
UPDATE static_countries SET cn_short_pl = 'Sudan', cn_official_name_pl = 'Republika Sudanu', cn_capital_pl = 'Chartum' WHERE cn_iso_2 = 'SD';
UPDATE static_countries SET cn_short_pl = 'Szwecja', cn_official_name_pl = 'Królestwo Szwecji', cn_capital_pl = 'Sztokholm' WHERE cn_iso_2 = 'SE';
UPDATE static_countries SET cn_short_pl = 'Singapur', cn_official_name_pl = 'Republika Singapuru', cn_capital_pl = cn_short_pl WHERE cn_iso_2 = 'SG';
UPDATE static_countries SET cn_short_pl = 'Wyspa Świętej Heleny', cn_official_name_pl = 'Wyspa Świętej Heleny, Wyspa Wniebowstąpienia i Tristan da Cunha', cn_capital_pl = 'Jamestown' WHERE cn_iso_2 = 'SH';
UPDATE static_countries SET cn_short_pl = 'Słowenia', cn_official_name_pl = 'Republika Słowenii', cn_capital_pl = 'Lublana' WHERE cn_iso_2 = 'SI';
UPDATE static_countries SET cn_short_pl = 'Svalbard i Jan Mayen', cn_capital_pl = 'Longyearbyen' WHERE cn_iso_2 = 'SJ';
UPDATE static_countries SET cn_short_pl = 'Słowacja', cn_official_name_pl = 'Republika Słowacka', cn_capital_pl = 'Bratysława' WHERE cn_iso_2 = 'SK';
UPDATE static_countries SET cn_short_pl = 'Sierra Leone', cn_official_name_pl = 'Republika Sierra Leone', cn_capital_pl = 'Freetown' WHERE cn_iso_2 = 'SL';
UPDATE static_countries SET cn_short_pl = 'San Marino', cn_official_name_pl = 'Najjaśniejsza Republika San Marino', cn_capital_pl = cn_short_pl WHERE cn_iso_2 = 'SM';
UPDATE static_countries SET cn_short_pl = 'Senegal', cn_official_name_pl = 'Republika Senegalu', cn_capital_pl = 'Dakar' WHERE cn_iso_2 = 'SN';
UPDATE static_countries SET cn_short_pl = 'Somalia', cn_official_name_pl = 'Republika Somalijska', cn_capital_pl = 'Mogadiszu' WHERE cn_iso_2 = 'SO';
UPDATE static_countries SET cn_short_pl = 'Surinam', cn_official_name_pl = 'Republika Surinam', cn_capital_pl = 'Paramaribo' WHERE cn_iso_2 = 'SR';
UPDATE static_countries SET cn_short_pl = 'Wyspy Świętego Tomasza i Książęca', cn_official_name_pl = 'Demokratyczna Republika Wysp Świętego Tomasza i Książęce', cn_capital_pl = 'São Tomé' WHERE cn_iso_2 = 'ST';
UPDATE static_countries SET cn_short_pl = 'Salwador', cn_official_name_pl = 'Republika Salwadoru', cn_capital_pl = 'San Salvador' WHERE cn_iso_2 = 'SV';
UPDATE static_countries SET cn_short_pl = 'Syria', cn_official_name_pl = 'Syryjska Republika Arabska', cn_capital_pl = 'Damaszek' WHERE cn_iso_2 = 'SY';
UPDATE static_countries SET cn_short_pl = 'Suazi', cn_official_name_pl = 'Królestwo Suazi', cn_capital_pl = 'Mbabane' WHERE cn_iso_2 = 'SZ';
UPDATE static_countries SET cn_short_pl = 'Turks i Caicos', cn_capital_pl = 'Cockburn Town' WHERE cn_iso_2 = 'TC';
UPDATE static_countries SET cn_short_pl = 'Czad', cn_official_name_pl = 'Republika Czadu', cn_capital_pl = 'Ndżamena' WHERE cn_iso_2 = 'TD';
UPDATE static_countries SET cn_short_pl = 'Francuskie Terytoria Południowe i Antarktyczne' WHERE cn_iso_2 = 'TF';
UPDATE static_countries SET cn_short_pl = 'Togo', cn_official_name_pl = 'Republika Togijska', cn_capital_pl = 'Lomé' WHERE cn_iso_2 = 'TG';
UPDATE static_countries SET cn_short_pl = 'Tajlandia', cn_official_name_pl = 'Królestwo Tajlandii', cn_capital_pl = 'Bangkok' WHERE cn_iso_2 = 'TH';
UPDATE static_countries SET cn_short_pl = 'Tadżykistan', cn_official_name_pl = 'Republika Tadżykistanu', cn_capital_pl = 'Duszanbe' WHERE cn_iso_2 = 'TJ';
UPDATE static_countries SET cn_short_pl = 'Tokelau' WHERE cn_iso_2 = 'TK';
UPDATE static_countries SET cn_short_pl = 'Turkmenistan', cn_capital_pl = 'Aszchabad' WHERE cn_iso_2 = 'TM';
UPDATE static_countries SET cn_short_pl = 'Tunezja', cn_official_name_pl = 'Republika Tunezyjska', cn_capital_pl = 'Tunis' WHERE cn_iso_2 = 'TN';
UPDATE static_countries SET cn_short_pl = 'Tonga', cn_official_name_pl = 'Królestwo Tonga', cn_capital_pl = 'Nukuʻalofa' WHERE cn_iso_2 = 'TO';
UPDATE static_countries SET cn_short_pl = 'Timor Wschodni', cn_official_name_pl = 'Demokratyczna Republika Timoru Wschodniego', cn_capital_pl = 'Dili' WHERE cn_iso_2 = 'TL';
UPDATE static_countries SET cn_short_pl = 'Turcja', cn_official_name_pl = 'Republika Turcji', cn_capital_pl = 'Ankara' WHERE cn_iso_2 = 'TR';
UPDATE static_countries SET cn_short_pl = 'Trynidad i Tobago', cn_capital_pl = 'Port-of-Spain' WHERE cn_iso_2 = 'TT';
UPDATE static_countries SET cn_short_pl = 'Tuvalu', cn_capital_pl = 'Vaiaku' WHERE cn_iso_2 = 'TV';
UPDATE static_countries SET cn_short_pl = 'Tajwan', cn_official_name_pl = 'Republika Chińska', cn_capital_pl = 'Tajpej' WHERE cn_iso_2 = 'TW';
UPDATE static_countries SET cn_short_pl = 'Tanzania', cn_official_name_pl = 'Zjednoczona Republika Tanzanii', cn_capital_pl = 'Dodoma' WHERE cn_iso_2 = 'TZ';
UPDATE static_countries SET cn_short_pl = 'Ukraina', cn_capital_pl = 'Kijów' WHERE cn_iso_2 = 'UA';
UPDATE static_countries SET cn_short_pl = 'Uganda', cn_official_name_pl = 'Republika Ugandy', cn_capital_pl = 'Kampala' WHERE cn_iso_2 = 'UG';
UPDATE static_countries SET cn_short_pl = 'Dalekie Wyspy Mniejsze Stanów Zjednoczonych' WHERE cn_iso_2 = 'UM';
UPDATE static_countries SET cn_short_pl = 'Stany Zjednoczone', cn_official_name_pl = 'Stany Zjednoczone Ameryki', cn_capital_pl = 'Waszyngton'  WHERE cn_iso_2 = 'US';
UPDATE static_countries SET cn_short_pl = 'Urugwaj', cn_official_name_pl = 'Wschodnia Republika Urugwaju', cn_capital_pl = 'Montevideo' WHERE cn_iso_2 = 'UY';
UPDATE static_countries SET cn_short_pl = 'Uzbekistan', cn_official_name_pl = 'Republika Uzbekistanu', cn_capital_pl = 'Taszkent' WHERE cn_iso_2 = 'UZ';
UPDATE static_countries SET cn_short_pl = 'Watykan', cn_official_name_pl = 'Państwo Miasta Watykańskiego', cn_capital_pl = cn_short_pl WHERE cn_iso_2 = 'VA';
UPDATE static_countries SET cn_short_pl = 'Saint Vincent i Grenadyny', cn_capital_pl = 'Kingstown' WHERE cn_iso_2 = 'VC';
UPDATE static_countries SET cn_short_pl = 'Wenezuela', cn_official_name_pl = 'Boliwariańska Republika Wenezueli', cn_capital_pl = 'Caracas' WHERE cn_iso_2 = 'VE';
UPDATE static_countries SET cn_short_pl = 'Brytyjskie Wyspy Dziewicze', cn_capital_pl = 'Road Town' WHERE cn_iso_2 = 'VG';
UPDATE static_countries SET cn_short_pl = 'Wyspy Dziewicze Stanów Zjednoczonych', cn_capital_pl = 'Charlotte Amalie' WHERE cn_iso_2 = 'VI';
UPDATE static_countries SET cn_short_pl = 'Wietnam', cn_official_name_pl = 'Socjalistyczna Republika Wietnamu', cn_capital_pl = 'Hanoi' WHERE cn_iso_2 = 'VN';
UPDATE static_countries SET cn_short_pl = 'Vanuatu', cn_official_name_pl = 'Republika Vanuatu', cn_capital_pl = 'Port Vila' WHERE cn_iso_2 = 'VU';
UPDATE static_countries SET cn_short_pl = 'Wallis i Futuna', cn_official_name_pl = 'Terytorium Wysp Wallis i Futuna', cn_capital_pl = 'Mata Utu' WHERE cn_iso_2 = 'WF';
UPDATE static_countries SET cn_short_pl = 'Samoa', cn_official_name_pl = 'Niezależne Państwo Samoa', cn_capital_pl = 'Apia' WHERE cn_iso_2 = 'WS';
UPDATE static_countries SET cn_short_pl = 'Jemen', cn_official_name_pl = 'Republika Jemeńska', cn_capital_pl = 'Sana' WHERE cn_iso_2 = 'YE';
UPDATE static_countries SET cn_short_pl = 'Majotta', cn_official_name_pl = 'Departament Zamorski Francji Majotta', cn_capital_pl = 'Mamoudzou' WHERE cn_iso_2 = 'YT';
UPDATE static_countries SET cn_short_pl = 'Republika Południowej Afryki', cn_capital_pl = 'Pretoria' WHERE cn_iso_2 = 'ZA';
UPDATE static_countries SET cn_short_pl = 'Zambia', cn_official_name_pl = 'Republika Zambii', cn_capital_pl = 'Lusaka' WHERE cn_iso_2 = 'ZM';
UPDATE static_countries SET cn_short_pl = 'Zimbabwe', cn_official_name_pl = 'Republika Zimbabwe', cn_capital_pl = 'Harare' WHERE cn_iso_2 = 'ZW';
UPDATE static_countries SET cn_short_pl = 'Autonomia Palestyńska', cn_official_name_pl = 'Palestyńskie Władze Narodowe', cn_capital_pl = 'Ramallah' WHERE cn_iso_2 = 'PS';
UPDATE static_countries SET cn_short_pl = 'Wyspy Alandzkie', cn_capital_pl = 'Maarianhamina' WHERE cn_iso_2 = 'AX';
UPDATE static_countries SET cn_short_pl = 'Wyspy Heard i McDonalda', cn_official_name_pl = 'Terytorium Wysp Heard i McDonalda' WHERE cn_iso_2 = 'HM';
UPDATE static_countries SET cn_short_pl = 'Czarnogóra', cn_official_name_pl = 'Republika Czarnogóry', cn_capital_pl = 'Podgorica' WHERE cn_iso_2 = 'ME';
UPDATE static_countries SET cn_short_pl = 'Serbia', cn_official_name_pl = 'Republika Serbii', cn_capital_pl = 'Belgrad' WHERE cn_iso_2 = 'RS';
UPDATE static_countries SET cn_short_pl = 'Jersey', cn_official_name_pl = 'Baliwat Jersey', cn_capital_pl = 'Saint Helier' WHERE cn_iso_2 = 'JE';
UPDATE static_countries SET cn_short_pl = 'Guernsey', cn_official_name_pl = 'Baliwat Guernsey', cn_capital_pl = 'Saint Peter Port' WHERE cn_iso_2 = 'GG';
UPDATE static_countries SET cn_short_pl = 'Wyspa Man', cn_capital_pl = 'Douglas' WHERE cn_iso_2 = 'IM';
UPDATE static_countries SET cn_short_pl = 'Saint-Martin', cn_official_name_pl = 'Wspólnota Saint-Martin', cn_capital_pl = 'Marigot' WHERE cn_iso_2 = 'MF';
UPDATE static_countries SET cn_short_pl = 'Saint-Barthélemy', cn_official_name_pl = 'Wspólnota Saint-Barthélemy', cn_capital_pl = 'Gustavia' WHERE cn_iso_2 = 'BL';
UPDATE static_countries SET cn_short_pl = 'Bonaire, Sint Eustatius i Saba' WHERE cn_iso_2 = 'BQ';
UPDATE static_countries SET cn_short_pl = 'Curaçao', cn_capital_pl = 'Willemstad' WHERE cn_iso_2 = 'CW';
UPDATE static_countries SET cn_short_pl = 'Sint Maarten', cn_capital_pl = 'Philipsburg' WHERE cn_iso_2 = 'SX';
UPDATE static_countries SET cn_short_pl = 'Sudan Południowy' WHERE cn_iso_2 = 'SS';
UPDATE static_countries SET cn_short_pl = 'Kosowo', cn_official_name_pl = 'Republika Kosowa', cn_capital_pl = 'Prisztina' WHERE cn_iso_2 ='XK';
UPDATE static_countries SET cn_official_name_pl = cn_short_pl WHERE cn_official_name_pl='' OR cn_official_name_pl IS NULL;


## static_country_zones
UPDATE static_country_zones SET zn_name_pl = 'Alabama' WHERE zn_country_iso_2 = 'US' AND zn_code = 'AL';
UPDATE static_country_zones SET zn_name_pl = 'Alaska' WHERE zn_country_iso_2 = 'US' AND zn_code = 'AK';
UPDATE static_country_zones SET zn_name_pl = 'Arizona' WHERE zn_country_iso_2 = 'US' AND zn_code = 'AZ';
UPDATE static_country_zones SET zn_name_pl = 'Arkansas' WHERE zn_country_iso_2 = 'US' AND zn_code = 'AR';
UPDATE static_country_zones SET zn_name_pl = 'Kalifornien' WHERE zn_country_iso_2 = 'US' AND zn_code = 'CA';
UPDATE static_country_zones SET zn_name_pl = 'Kalifornia' WHERE zn_country_iso_2 = 'US' AND zn_code = 'CO';
UPDATE static_country_zones SET zn_name_pl = 'Connecticut' WHERE zn_country_iso_2 = 'US' AND zn_code = 'CT';
UPDATE static_country_zones SET zn_name_pl = 'Delaware' WHERE zn_country_iso_2 = 'US' AND zn_code = 'DE';
UPDATE static_country_zones SET zn_name_pl = 'Dystrykt Kolumbia' WHERE zn_country_iso_2 = 'US' AND zn_code = 'DC';
UPDATE static_country_zones SET zn_name_pl = 'Floryda' WHERE zn_country_iso_2 = 'US' AND zn_code = 'FL';
UPDATE static_country_zones SET zn_name_pl = 'Georgia' WHERE zn_country_iso_2 = 'US' AND zn_code = 'GA';
UPDATE static_country_zones SET zn_name_pl = 'Guam' WHERE zn_country_iso_2 = 'US' AND zn_code = 'GU';
UPDATE static_country_zones SET zn_name_pl = 'Hawaje' WHERE zn_country_iso_2 = 'US' AND zn_code = 'HI';
UPDATE static_country_zones SET zn_name_pl = 'Idaho' WHERE zn_country_iso_2 = 'US' AND zn_code = 'ID';
UPDATE static_country_zones SET zn_name_pl = 'Illinois' WHERE zn_country_iso_2 = 'US' AND zn_code = 'IL';
UPDATE static_country_zones SET zn_name_pl = 'Indiana' WHERE zn_country_iso_2 = 'US' AND zn_code = 'IN';
UPDATE static_country_zones SET zn_name_pl = 'Iowa' WHERE zn_country_iso_2 = 'US' AND zn_code = 'IA';
UPDATE static_country_zones SET zn_name_pl = 'Kansas' WHERE zn_country_iso_2 = 'US' AND zn_code = 'KS';
UPDATE static_country_zones SET zn_name_pl = 'Kentucky' WHERE zn_country_iso_2 = 'US' AND zn_code = 'KY';
UPDATE static_country_zones SET zn_name_pl = 'Luizjana' WHERE zn_country_iso_2 = 'US' AND zn_code = 'LA';
UPDATE static_country_zones SET zn_name_pl = 'Maine' WHERE zn_country_iso_2 = 'US' AND zn_code = 'ME';
UPDATE static_country_zones SET zn_name_pl = 'Maryland' WHERE zn_country_iso_2 = 'US' AND zn_code = 'MD';
UPDATE static_country_zones SET zn_name_pl = 'Massachusetts' WHERE zn_country_iso_2 = 'US' AND zn_code = 'MA';
UPDATE static_country_zones SET zn_name_pl = 'Michigan' WHERE zn_country_iso_2 = 'US' AND zn_code = 'MI';
UPDATE static_country_zones SET zn_name_pl = 'Minnesota' WHERE zn_country_iso_2 = 'US' AND zn_code = 'MN';
UPDATE static_country_zones SET zn_name_pl = 'Missisipi' WHERE zn_country_iso_2 = 'US' AND zn_code = 'MS';
UPDATE static_country_zones SET zn_name_pl = 'Missouri' WHERE zn_country_iso_2 = 'US' AND zn_code = 'MO';
UPDATE static_country_zones SET zn_name_pl = 'Montana' WHERE zn_country_iso_2 = 'US' AND zn_code = 'MT';
UPDATE static_country_zones SET zn_name_pl = 'Nebraska' WHERE zn_country_iso_2 = 'US' AND zn_code = 'NE';
UPDATE static_country_zones SET zn_name_pl = 'Nevada' WHERE zn_country_iso_2 = 'US' AND zn_code = 'NV';
UPDATE static_country_zones SET zn_name_pl = 'New Hampshire' WHERE zn_country_iso_2 = 'US' AND zn_code = 'NH';
UPDATE static_country_zones SET zn_name_pl = 'New Jersey' WHERE zn_country_iso_2 = 'US' AND zn_code = 'NJ';
UPDATE static_country_zones SET zn_name_pl = 'Nowy Meksyk' WHERE zn_country_iso_2 = 'US' AND zn_code = 'NM';
UPDATE static_country_zones SET zn_name_pl = 'Nowy Jork' WHERE zn_country_iso_2 = 'US' AND zn_code = 'NY';
UPDATE static_country_zones SET zn_name_pl = 'Karolina Północna' WHERE zn_country_iso_2 = 'US' AND zn_code = 'NC';
UPDATE static_country_zones SET zn_name_pl = 'Dakota Północna' WHERE zn_country_iso_2 = 'US' AND zn_code = 'ND';
UPDATE static_country_zones SET zn_name_pl = 'Ohio' WHERE zn_country_iso_2 = 'US' AND zn_code = 'OH';
UPDATE static_country_zones SET zn_name_pl = 'Oklahoma' WHERE zn_country_iso_2 = 'US' AND zn_code = 'OK';
UPDATE static_country_zones SET zn_name_pl = 'Oregon' WHERE zn_country_iso_2 = 'US' AND zn_code = 'OR';
UPDATE static_country_zones SET zn_name_pl = 'Pensylwania' WHERE zn_country_iso_2 = 'US' AND zn_code = 'PA';
UPDATE static_country_zones SET zn_name_pl = 'Portoryko' WHERE zn_country_iso_2 = 'US' AND zn_code = 'PR';
UPDATE static_country_zones SET zn_name_pl = 'Rhode Island' WHERE zn_country_iso_2 = 'US' AND zn_code = 'RI';
UPDATE static_country_zones SET zn_name_pl = 'Karolina Południowa' WHERE zn_country_iso_2 = 'US' AND zn_code = 'SC';
UPDATE static_country_zones SET zn_name_pl = 'Dakota Południowa' WHERE zn_country_iso_2 = 'US' AND zn_code = 'SD';
UPDATE static_country_zones SET zn_name_pl = 'Tennessee' WHERE zn_country_iso_2 = 'US' AND zn_code = 'TN';
UPDATE static_country_zones SET zn_name_pl = 'Teksas' WHERE zn_country_iso_2 = 'US' AND zn_code = 'TX';
UPDATE static_country_zones SET zn_name_pl = 'Utah' WHERE zn_country_iso_2 = 'US' AND zn_code = 'UT';
UPDATE static_country_zones SET zn_name_pl = 'Vermont' WHERE zn_country_iso_2 = 'US' AND zn_code = 'VT';
UPDATE static_country_zones SET zn_name_pl = 'Wirginia' WHERE zn_country_iso_2 = 'US' AND zn_code = 'VA';
UPDATE static_country_zones SET zn_name_pl = 'Waszyngton' WHERE zn_country_iso_2 = 'US' AND zn_code = 'WA';
UPDATE static_country_zones SET zn_name_pl = 'Wirginia Zachodnia' WHERE zn_country_iso_2 = 'US' AND zn_code = 'WV';
UPDATE static_country_zones SET zn_name_pl = 'Wisconsin' WHERE zn_country_iso_2 = 'US' AND zn_code = 'WI';
UPDATE static_country_zones SET zn_name_pl = 'Wyoming' WHERE zn_country_iso_2 = 'US' AND zn_code = 'WY';


## Update for data inserted previously by static_info_tables
UPDATE static_country_zones SET zn_name_pl = zn_name_local WHERE zn_country_iso_2 = 'PL'


## static_currencies
UPDATE static_currencies SET cu_name_pl = 'Dolar australijski', cu_sub_name_pl = 'cent' WHERE cu_iso_3='AUD';
UPDATE static_currencies SET cu_name_pl = 'Marka zamienna', cu_sub_name_pl = 'fenig' WHERE cu_iso_3='BAM';
UPDATE static_currencies SET cu_name_pl = 'Lew', cu_sub_name_pl = 'stotinka' WHERE cu_iso_3='BGN';
UPDATE static_currencies SET cu_name_pl = 'Rubel białoruski', cu_sub_name_pl = 'kopiejka' WHERE cu_iso_3='BYR';
UPDATE static_currencies SET cu_name_pl = 'Dolar kanadyjski', cu_sub_name_pl = 'cent' WHERE cu_iso_3='CAD';
UPDATE static_currencies SET cu_name_pl = 'Frank szwajcarski', cu_sub_name_pl = 'centym' WHERE cu_iso_3='CHF';
UPDATE static_currencies SET cu_name_pl = 'Dinar serbski', cu_sub_name_pl = 'para' WHERE cu_iso_3='CSD';
UPDATE static_currencies SET cu_name_pl = 'Korona czeska', cu_sub_name_pl = 'halerz' WHERE cu_iso_3='CZK';
UPDATE static_currencies SET cu_name_pl = 'Korona duńska', cu_sub_name_pl = 'øre' WHERE cu_iso_3='DKK';
UPDATE static_currencies SET cu_name_pl = 'Euro', cu_sub_name_pl = 'cent' WHERE cu_iso_3='EUR';
UPDATE static_currencies SET cu_name_pl = 'Funt brytyjski', cu_sub_name_pl = 'pens' WHERE cu_iso_3='GBP';
UPDATE static_currencies SET cu_name_pl = 'Forint wegierski', cu_sub_name_pl = '' WHERE cu_iso_3='HUF';
UPDATE static_currencies SET cu_name_pl = 'Kuna', cu_sub_name_pl = 'lip' WHERE cu_iso_3='HRK';
UPDATE static_currencies SET cu_name_pl = 'Korona islandzka', cu_sub_name_pl = 'aurar' WHERE cu_iso_3='ISK';
UPDATE static_currencies SET cu_name_pl = 'Jen japoński', cu_sub_name_pl = 'sen' WHERE cu_iso_3='JPY';
UPDATE static_currencies SET cu_name_pl = 'Lit litewski', cu_sub_name_pl = 'cent' WHERE cu_iso_3='LTL';
UPDATE static_currencies SET cu_name_pl = 'Lej mołdawski', cu_sub_name_pl = 'ban' WHERE cu_iso_3='MDL';
UPDATE static_currencies SET cu_name_pl = 'Denar macedoński', cu_sub_name_pl = 'deni' WHERE cu_iso_3='MKD';
UPDATE static_currencies SET cu_name_pl = 'Korona norweska', cu_sub_name_pl = 'øre' WHERE cu_iso_3='NOK';
UPDATE static_currencies SET cu_name_pl = 'Złoty polski', cu_sub_name_pl = 'grosz', cu_thousands_point = ' ', cu_decimal_point = ',', cu_sub_symbol_right = 'gr' WHERE cu_iso_3='PLN';
UPDATE static_currencies SET cu_name_pl = 'Lej', cu_sub_name_pl = 'ban' WHERE cu_iso_3='RON';
UPDATE static_currencies SET cu_name_pl = 'Rubel rosyjski', cu_sub_name_pl = 'kopiejka' WHERE cu_iso_3='RUB';
UPDATE static_currencies SET cu_name_pl = 'Korona szwedzka', cu_sub_name_pl = 'öre' WHERE cu_iso_3='SEK';
UPDATE static_currencies SET cu_name_pl = 'Hrywna', cu_sub_name_pl = 'kopiejka' WHERE cu_iso_3='UAH';
UPDATE static_currencies SET cu_name_pl = 'Dolar amerykański', cu_sub_name_pl = 'cent' WHERE cu_iso_3='USD';


UPDATE static_languages SET lg_name_pl = 'abchaski' WHERE lg_iso_2 = 'AB' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'afar' WHERE lg_iso_2 = 'AA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'afrykanerski' WHERE lg_iso_2 = 'AF' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'albański' WHERE lg_iso_2 = 'SQ' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'amharski' WHERE lg_iso_2 = 'AM' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'arabski' WHERE lg_iso_2 = 'AR' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'ormiański' WHERE lg_iso_2 = 'HY' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'assamski' WHERE lg_iso_2 = 'AS' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'ajmara' WHERE lg_iso_2 = 'AY' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'azerski' WHERE lg_iso_2 = 'AZ' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'baszkirski' WHERE lg_iso_2 = 'BA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'baskijski' WHERE lg_iso_2 = 'EU' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'bengalski' WHERE lg_iso_2 = 'BN' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'dzongkha' WHERE lg_iso_2 = 'DZ' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'bihari' WHERE lg_iso_2 = 'BH' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'bislama' WHERE lg_iso_2 = 'BI' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'bretoński' WHERE lg_iso_2 = 'BR' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'bułgarski' WHERE lg_iso_2 = 'BG' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'birmański' WHERE lg_iso_2 = 'MY' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'białoruski' WHERE lg_iso_2 = 'BE' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'khmerski' WHERE lg_iso_2 = 'KM' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'kataloński' WHERE lg_iso_2 = 'CA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'zhuang' WHERE lg_iso_2 = 'ZA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'chiński (tracycyjny)' WHERE lg_iso_2 = 'ZH' AND lg_country_iso_2 = 'HK';
UPDATE static_languages SET lg_name_pl = 'korsykański' WHERE lg_iso_2 = 'CO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'chorwacki' WHERE lg_iso_2 = 'HR' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'czeski' WHERE lg_iso_2 = 'CS' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'duński' WHERE lg_iso_2 = 'DA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'holenderski' WHERE lg_iso_2 = 'NL' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'angielski' WHERE lg_iso_2 = 'EN' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'esperanto' WHERE lg_iso_2 = 'EO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'estoński' WHERE lg_iso_2 = 'ET' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'farerski' WHERE lg_iso_2 = 'FO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'perski' WHERE lg_iso_2 = 'FA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'fidżyjski' WHERE lg_iso_2 = 'FJ' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'fiński' WHERE lg_iso_2 = 'FI' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'francuski' WHERE lg_iso_2 = 'FR' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'francuski kanadyjski' WHERE lg_iso_2 = 'FR' AND lg_country_iso_2 = 'CA';
UPDATE static_languages SET lg_name_pl = 'fryzyjski' WHERE lg_iso_2 = 'FY' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'galicyjski' WHERE lg_iso_2 = 'GL' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'gaelicki szkocki' WHERE lg_iso_2 = 'GD' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'manks' WHERE lg_iso_2 = 'GV' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'gruziński' WHERE lg_iso_2 = 'KA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'niemiecki' WHERE lg_iso_2 = 'DE' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'nowogrecki' WHERE lg_iso_2 = 'EL' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'grenlandzki' WHERE lg_iso_2 = 'KL' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'guarani' WHERE lg_iso_2 = 'GN' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'gudźarati' WHERE lg_iso_2 = 'GU' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'hausa' WHERE lg_iso_2 = 'HA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'hebrajski' WHERE lg_iso_2 = 'HE' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'hindi' WHERE lg_iso_2 = 'HI' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'węgierski' WHERE lg_iso_2 = 'HU' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'islandzki' WHERE lg_iso_2 = 'IS' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'indonezyjski' WHERE lg_iso_2 = 'ID' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'inuktitut' WHERE lg_iso_2 = 'IU' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'inupiak' WHERE lg_iso_2 = 'IK' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'irlandzki' WHERE lg_iso_2 = 'GA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'włoski' WHERE lg_iso_2 = 'IT' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'japoński' WHERE lg_iso_2 = 'JA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'kannada' WHERE lg_iso_2 = 'KN' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'kaszmirski' WHERE lg_iso_2 = 'KS' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'kazachski' WHERE lg_iso_2 = 'KK' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'ruanda-rundi (kinyarwanda)' WHERE lg_iso_2 = 'RW' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'kirgiski' WHERE lg_iso_2 = 'KY' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'rundi' WHERE lg_iso_2 = 'RN' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'koreański' WHERE lg_iso_2 = 'KO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'kurtyjski' WHERE lg_iso_2 = 'KU' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'laotański' WHERE lg_iso_2 = 'LO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'łotewski' WHERE lg_iso_2 = 'LV' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'lingala' WHERE lg_iso_2 = 'LN' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'litewski' WHERE lg_iso_2 = 'LT' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'macedoński' WHERE lg_iso_2 = 'MK' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'malgaski' WHERE lg_iso_2 = 'MG' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'malajski' WHERE lg_iso_2 = 'MS' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'malajalam' WHERE lg_iso_2 = 'ML' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'maltański' WHERE lg_iso_2 = 'MT' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'maoryski' WHERE lg_iso_2 = 'MI' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'marathi' WHERE lg_iso_2 = 'MR' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'mołdawski' WHERE lg_iso_2 = 'MO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'mongolski' WHERE lg_iso_2 = 'MN' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'nauruański' WHERE lg_iso_2 = 'NA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'nepalski' WHERE lg_iso_2 = 'NE' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'norweski' WHERE lg_iso_2 = 'NO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'gaskoński' WHERE lg_iso_2 = 'OC' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'orija' WHERE lg_iso_2 = 'OR' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'oromo' WHERE lg_iso_2 = 'OM' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'paszto' WHERE lg_iso_2 = 'PS' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'polski' WHERE lg_iso_2 = 'PL' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'portugalski' WHERE lg_iso_2 = 'PT' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'pendżabski' WHERE lg_iso_2 = 'PA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'keczua' WHERE lg_iso_2 = 'QU' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'romansz' WHERE lg_iso_2 = 'RM' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'rumuński' WHERE lg_iso_2 = 'RO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'rosyjski' WHERE lg_iso_2 = 'RU' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'tongo' WHERE lg_iso_2 = 'SM' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'sango' WHERE lg_iso_2 = 'SG' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'serbski' WHERE lg_iso_2 = 'SR' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'sotho' WHERE lg_iso_2 = 'ST' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'setswana' WHERE lg_iso_2 = 'TN' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'shona' WHERE lg_iso_2 = 'SN' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'sindhi' WHERE lg_iso_2 = 'SD' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'syngaleski' WHERE lg_iso_2 = 'SI' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'suazi' WHERE lg_iso_2 = 'SS' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'słowacki' WHERE lg_iso_2 = 'SK' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'słoweński' WHERE lg_iso_2 = 'SL' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'somalijski' WHERE lg_iso_2 = 'SO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'hiszpański' WHERE lg_iso_2 = 'ES' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'sundajski' WHERE lg_iso_2 = 'SU' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'suahili' WHERE lg_iso_2 = 'SW' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'szwedzki' WHERE lg_iso_2 = 'SV' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'tagalski' WHERE lg_iso_2 = 'TL' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'filipiński' WHERE lg_iso_2 = 'TL' AND lg_country_iso_2 = 'PH';
UPDATE static_languages SET lg_name_pl = 'tadżycki' WHERE lg_iso_2 = 'TG' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'tamilski' WHERE lg_iso_2 = 'TA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'tatarski' WHERE lg_iso_2 = 'TT' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'telugu' WHERE lg_iso_2 = 'TE' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'tajski' WHERE lg_iso_2 = 'TH' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'tybetański' WHERE lg_iso_2 = 'BO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'tigrinia' WHERE lg_iso_2 = 'TI' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'tonga' WHERE lg_iso_2 = 'TO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'tswana' WHERE lg_iso_2 = 'TS' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'turecki' WHERE lg_iso_2 = 'TR' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'turkmeński' WHERE lg_iso_2 = 'TK' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'twi' WHERE lg_iso_2 = 'TW' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'ujgurski' WHERE lg_iso_2 = 'UG' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'ukraiński' WHERE lg_iso_2 = 'UK' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'urdu' WHERE lg_iso_2 = 'UR' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'uzbecki' WHERE lg_iso_2 = 'UZ' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'wietnamski' WHERE lg_iso_2 = 'VI' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'walijski' WHERE lg_iso_2 = 'CY' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'wolof' WHERE lg_iso_2 = 'WO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'xhosa' WHERE lg_iso_2 = 'XH' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'joruba' WHERE lg_iso_2 = 'YO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'zulu' WHERE lg_iso_2 = 'ZU' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'bośniacki' WHERE lg_iso_2 = 'BS' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'akański' WHERE lg_iso_2 = 'AK' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'aragoński' WHERE lg_iso_2 = 'AN' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'awarski' WHERE lg_iso_2 = 'AV' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'bambara' WHERE lg_iso_2 = 'BM' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'czeczeński' WHERE lg_iso_2 = 'CE' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'czarnogórski' WHERE lg_iso_2 = 'CH' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'kri' WHERE lg_iso_2 = 'CR' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'czuwaski' WHERE lg_iso_2 = 'CV' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'malediwski' WHERE lg_iso_2 = 'DV' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'ewe' WHERE lg_iso_2 = 'EE' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'ful' WHERE lg_iso_2 = 'FF' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'hiri motu' WHERE lg_iso_2 = 'HO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'haitański' WHERE lg_iso_2 = 'HT' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'herero' WHERE lg_iso_2 = 'HZ' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'igbo' WHERE lg_iso_2 = 'IG' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'yi' WHERE lg_iso_2 = 'II' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'kongo' WHERE lg_iso_2 = 'KG' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'kikuju' WHERE lg_iso_2 = 'KI' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'kwanyama' WHERE lg_iso_2 = 'KJ' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'kanuri' WHERE lg_iso_2 = 'KR' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'komi' WHERE lg_iso_2 = 'KV' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'kornijski' WHERE lg_iso_2 = 'KW' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'luksemburski' WHERE lg_iso_2 = 'LB' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'luganda' WHERE lg_iso_2 = 'LG' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'limburski' WHERE lg_iso_2 = 'LI' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'luba' WHERE lg_iso_2 = 'LU' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'marszalski' WHERE lg_iso_2 = 'MH' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'norweski (bokmål)' WHERE lg_iso_2 = 'NB' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'ndebele północny' WHERE lg_iso_2 = 'ND' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'ndonga' WHERE lg_iso_2 = 'NG' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'norweski (nynorsk)' WHERE lg_iso_2 = 'NN' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'ndebele południowy' WHERE lg_iso_2 = 'NR' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'nawaho' WHERE lg_iso_2 = 'NV' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'cziczewa' WHERE lg_iso_2 = 'NY' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'odżibwe' WHERE lg_iso_2 = 'OJ' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'osetyjski' WHERE lg_iso_2 = 'OS' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'sardyński' WHERE lg_iso_2 = 'SC' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'północno samaryjski' WHERE lg_iso_2 = 'SE' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'tahitański' WHERE lg_iso_2 = 'TY' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'venda' WHERE lg_iso_2 = 'VE' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'waloński' WHERE lg_iso_2 = 'WA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'jawajski' WHERE lg_iso_2 = 'JV' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'portugalski' WHERE lg_iso_2 = 'PT' AND lg_country_iso_2 = 'BR';
UPDATE static_languages SET lg_name_pl = 'chiński (uproszczony)' WHERE lg_iso_2 = 'ZH' AND lg_country_iso_2 = 'CN';
UPDATE static_languages SET lg_name_pl = 'interlingua' WHERE lg_iso_2 = 'IA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'interlingue' WHERE lg_iso_2 = 'IE' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'łaciński' WHERE lg_iso_2 = 'LA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'sanskryt' WHERE lg_iso_2 = 'SA' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'volapük' WHERE lg_iso_2 = 'VO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'jidysz' WHERE lg_iso_2 = 'YI' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'awestyjski' WHERE lg_iso_2 = 'AE' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'staro-cerkiewno-słowiański' WHERE lg_iso_2 = 'CU' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'ido' WHERE lg_iso_2 = 'IO' AND lg_country_iso_2 = '';
UPDATE static_languages SET lg_name_pl = 'pali' WHERE lg_iso_2 = 'PI' AND lg_country_iso_2 = '';

## static_territories
UPDATE static_territories SET tr_name_pl = 'Afryka' WHERE tr_iso_nr = '2';
UPDATE static_territories SET tr_name_pl = 'Oceania' WHERE tr_iso_nr = '9';
UPDATE static_territories SET tr_name_pl = 'Ameryki północna, środkowa i południowa' WHERE tr_iso_nr = '19';
UPDATE static_territories SET tr_name_pl = 'Azja' WHERE tr_iso_nr = '142';
UPDATE static_territories SET tr_name_pl = 'Europa' WHERE tr_iso_nr = '150';
UPDATE static_territories SET tr_name_pl = 'Azja wschodnia' WHERE tr_iso_nr = '30';
UPDATE static_territories SET tr_name_pl = 'Azja południowo-wschodnia' WHERE tr_iso_nr = '35';
UPDATE static_territories SET tr_name_pl = 'Azja środkowa' WHERE tr_iso_nr = '143';
UPDATE static_territories SET tr_name_pl = 'Azja zachodnia' WHERE tr_iso_nr = '145';
UPDATE static_territories SET tr_name_pl = 'Europa południowa' WHERE tr_iso_nr = '39';
UPDATE static_territories SET tr_name_pl = 'Europa wschodnia' WHERE tr_iso_nr = '151';
UPDATE static_territories SET tr_name_pl = 'Europa północna' WHERE tr_iso_nr = '154';
UPDATE static_territories SET tr_name_pl = 'Eueopa zachodnia' WHERE tr_iso_nr = '155';
UPDATE static_territories SET tr_name_pl = 'Ameryka południowa' WHERE tr_iso_nr = '5';
UPDATE static_territories SET tr_name_pl = 'Ameryka środkowa' WHERE tr_iso_nr = '13';
UPDATE static_territories SET tr_name_pl = 'Ameryka północna' WHERE tr_iso_nr = '21';
UPDATE static_territories SET tr_name_pl = 'Karaiby' WHERE tr_iso_nr = '29';
UPDATE static_territories SET tr_name_pl = 'Ameryka zachodnia' WHERE tr_iso_nr = '11';
UPDATE static_territories SET tr_name_pl = 'Afryka wschodnia' WHERE tr_iso_nr = '14';
UPDATE static_territories SET tr_name_pl = 'Afryka północna' WHERE tr_iso_nr = '15';
UPDATE static_territories SET tr_name_pl = 'Afryka środkowa' WHERE tr_iso_nr = '17';
UPDATE static_territories SET tr_name_pl = 'Afryka południowa' WHERE tr_iso_nr = '18';
UPDATE static_territories SET tr_name_pl = 'Australia i Nowa Zelandia' WHERE tr_iso_nr = '53';
UPDATE static_territories SET tr_name_pl = 'Melanezja' WHERE tr_iso_nr = '54';
UPDATE static_territories SET tr_name_pl = 'Mikronezja' WHERE tr_iso_nr = '57';
UPDATE static_territories SET tr_name_pl = 'Polinezia' WHERE tr_iso_nr = '61';
UPDATE static_territories SET tr_name_pl = 'Azja południowa' WHERE tr_iso_nr = '34';